### ISSUE TITLE
Running `make install` on a new deployment fails due to `CodeStarNotifications`

### ISSUE THREAD

**Issue by davidfsmith** [aws-solutions-library-samples/guidance-for-aws-deepracer-event-management#65]
Running `make install` on a new deployment fails due to `CodeStarNotifications`

```
drem-pipeline-main: creating CloudFormation changeset...
16:58:26 | CREATE_FAILED        | AWS::CodeStarNotifications::NotificationRule | NotificationRule44229486
Resource handler returned message: "Invalid request provided: AWS::CodeStarNotifications::NotificationRule" (RequestToken: abf74393-352f-0fd6-2d08-7c612c397d59, HandlerErrorCode: InvalidRequest)


 ❌  drem-pipeline-main failed: Error: The stack named drem-pipeline-main failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: AWS::CodeStarNotifications::NotificationRule" (RequestToken: abf74393-352f-0fd6-2d08-7c612c397d59, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/Users/davidsmith/Documents/Development/deepracer/drem/node_modules/aws-cdk/lib/index.js:443:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.deployStack2 [as deployStack] (/Users/davidsmith/Documents/Development/deepracer/drem/node_modules/aws-cdk/lib/index.js:446:153718)
    at async /Users/davidsmith/Documents/Development/deepracer/drem/node_modules/aws-cdk/lib/index.js:446:137166

 ❌ Deployment failed: Error: The stack named drem-pipeline-main failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: AWS::CodeStarNotifications::NotificationRule" (RequestToken: abf74393-352f-0fd6-2d08-7c612c397d59, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/Users/davidsmith/Documents/Development/deepracer/drem/node_modules/aws-cdk/lib/index.js:443:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.deployStack2 [as deployStack] (/Users/davidsmith/Documents/Development/deepracer/drem/node_modules/aws-cdk/lib/index.js:446:153718)
    at async /Users/davidsmith/Documents/Development/deepracer/drem/node_modules/aws-cdk/lib/index.js:446:137166

The stack named drem-pipeline-main failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: AWS::CodeStarNotifications::NotificationRule" (RequestToken: abf74393-352f-0fd6-2d08-7c612c397d59, HandlerErrorCode: InvalidRequest)
make: *** [pipeline.deploy] Error 1
```

**Comment by davidfsmith** [comment]
Interestingly after running `make install` the build completed

**Comment by StevenAskwith** [comment]
Yes, I can replicate this bug.  

Th first `make install` fail, but if you re-run `make install` it will then run cleanly.  I think we have a race condition somewhere in the CDK/CloudFormation.

**Comment by davidfsmith** [comment]
I've not seen this happening in recent testing when deploying a fresh DREM install on v3 and above
